update line 147 to follow error suggestion
When I tried to run this script on amphiprion, returned this error:
  File "/local/home/michelles/14_programs/paired_sequence_utils/barcode_splitter.py", line 147
    print "Sample\tBarcode\tCount\tPercent"
                                          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "Sample\tBarcode\tCount\tPercent")?

Followed the suggestion